openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the service.
      responses:
        '200':
          description: Service is up and running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Health status message.
  /coffees:
    get:
      summary: Get all coffees
      description: Returns a list of all coffees.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Coffee'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Add a new coffee
      description: Adds a new coffee to the catalogue.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoffeeInput'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                  data:
                    $ref: '#/components/schemas/Coffee'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /coffees/{id}:
    get:
      summary: Get coffee by ID
      description: Returns a coffee by its ID.
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the coffee to retrieve
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                  data:
                    $ref: '#/components/schemas/Coffee'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Coffee not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Update coffee by ID
      description: Updates an existing coffee by its ID.
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the coffee to update
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoffeeInput'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                  data:
                    $ref: '#/components/schemas/Coffee'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Coffee not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      summary: Delete coffee by ID
      description: Deletes a coffee by its ID.
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the coffee to delete
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                  data:
                    type: string
                    description: ID of the deleted coffee
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Coffee not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Coffee:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the coffee
        name:
          type: string
          description: Name of the coffee
        description:
          type: string
          description: Description of the coffee
      required:
      - id
      - name
      - description
    CoffeeInput:
      type: object
      properties:
        name:
          type: string
          description: Name of the coffee
        description:
          type: string
          description: Description of the coffee
      required:
      - name
      - description
